### ISSUE TITLE
I2C Disabled

### ISSUE THREAD

**Issue by somacoder** [tianyoujian/MZDPI#4]
The use of this screen (Version-A 2.8 inch Touch Screen) appears to disable any use of I2C for other devices. Is there any way to enable use of I2C for other devices and still maintain functionality of the screen?

Thanks!

**Comment by Andreeved88** [comment]
sry for my russian english..i'm using mzdpi-vga-zero 2.8inch on zero w and have same problem. but solved)
add "dtoverlay=i2c-gpio,i2c_gpio_sda=25,i2c_gpio_scl=26" in boot/config.txt 
gpio25-sda-22 pin
gpio26-scl- 37 pin
bus i2c-3

**Comment by RyanWoirol** [comment]
> sry for my russian english..i'm using mzdpi-vga-zero 2.8inch on zero w and have same problem. but solved)
> add "dtoverlay=i2c-gpio,i2c_gpio_sda=25,i2c_gpio_scl=26" in boot/config.txt
> gpio25-sda-22 pin
> gpio26-scl- 37 pin
> bus i2c-3

I'm sorry but I'm not following this.  Is this 4 separate lines?  The spacing is weird and I'm not familiar with linux enough to be able to understand it's language and see what I would need to fix.

**Comment by toygar-12** [comment]
Is this same for Version-C?
